<?php 
	/**
	 * Implementation of hook_menu().
	*/
	function test_module_menu() {
		$items['search-test'] = array(
			'page callback' => 'search_box_test',
			'file' => 'test_module.pages.inc',
			'file path' => drupal_get_path('module', 'test_module') . '/inc/',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		);
		$items['result-search-test/%/%/%'] = array(
			'page callback' => 'result_search_test',
			'file' => 'test_module.pages.inc',
			'file path' => drupal_get_path('module', 'test_module') . '/inc/',
			'access callback' => TRUE,
			'page arguments' => array(1,2,3),
			'type' => MENU_CALLBACK,
		);
		return $items;
	}
	/**
	 * Implementation of hook_theme().
	*/
	function test_module_theme(){
		return array(
		'result_search' => array(
	            'template' => 'templates/result_search',
	            'variables' => array(
	                'items' => array(),
					)
	        ),
	    );
	}
?>